### ISSUE TITLE
Blocked by CORS policy

### ISSUE THREAD

**Issue by aelharda** [lehel-twilio/plugin-sms#6]
From the Chrome console (URL is x'd out):
 
Access to fetch at 'https://xxx-xxx.twil.io/create-new-sms' from origin 'https://flex.twilio.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by rmsdev0** [comment]
Did you ever solve this? Having the same issue.

**Comment by aelharda** [comment]
> Did you ever solve this? Having the same issue.

in the outbound sms function please add the following CORS headers:
`const axios = require('axios');

exports.handler = async function(context, event, callback) {
  const response = new Twilio.Response();
  response.appendHeader('Access-Control-Allow-Origin', '*');
  response.appendHeader('Access-Control-Allow-Methods', 'OPTIONS POST');
  response.appendHeader('Content-Type', 'application/json');
  response.appendHeader('Access-Control-Allow-Headers', 'Content-Type');`

**Comment by aelharda** [comment]
you can also use the following link: https://www.twilio.com/docs/runtime/functions/faq?code-sample=code-set-multiple-http-headers-in-a-response-5&code-language=Node.js&code-sdk-version=default
